### PR TITLE
Implementing lists (<ul>)

### PR DESCRIPTION
**Pull request by GuilloteauQ**
implemented unordered lists (<ul>), added an example and updated the README

### CODE REVIEW

**Comment by GuilloteauQ** [comment]
also implemented checkboxes (updated readme)

**Comment by LachlanMarnham** [comment]
@GuilloteauQ Does the work on checkboxes cross over with issue #23?

**Comment by GuilloteauQ** [comment]
@LachlanMarnham It should yes. I haven't done the "class" part though ..

**Comment by LachlanMarnham** [comment]
Ok, well then I will wait for somebody to merge your PR and then implement the classes.

**Comment by marcosstefani** [comment]
@LachlanMarnham Feel free.

**Pull request merged**
